version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    privileged: true
    restart: always
    volumes:
      - ./conf/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - TZ="Asia/Seoul
    depends_on:
      - jenkins-master

  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    hostname: jenkins-master
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - $HOME/jenkins_master:/var/jenkins_home
    ports:
      - 50000:50000
    environment:
      - TZ="Asia/Seoul"

  jenkins-agent01:
    image: jenkins/ssh-agent:latest
    container_name: jenkins-agent01
    hostname: jenkins-agent01
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - $HOME/jenkins_agent:/var/jenkins_home
    environment:
      - JENKINS_AGENT_SSH_PUBKEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLT3ZHpTr..."
      - TZ="Asia/Seoul"
