version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    privileged: true
    restart: always
    volumes:
      - ./conf/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - TZ="Asia/Seoul

  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - $HOME/jenkins_home2:/var/jenkins_home
    ports:
      # - 8080:8080
      - 50000:50000
    environment:
      - TZ="Asia/Seoul"
